### PR TITLE
Revert "Link reverse-isms to an apropos blog post"

### PR DESCRIPTION
**Pull request by rubinovitz**
Reverts HackathonHackers/code-of-conduct#7

I think footnotes might be better than a bunch of links in text.

### CODE REVIEW

**Comment by rubinovitz** [comment]
@kern  can we do footnotes?

**Comment by kern** [comment]
I don't think anyone will read footnotes. Why not embedded links in text?

**Comment by rubinovitz** [comment]
I don't see people who are actually going to read these caring whether its
a footnote or a link.

as far as why not embedded links in text: these rules have to be explained
to multiple people multiple times. I can see most of this document having
hyperlinks at some point. Rather than doing that, when someone ends up
having to explain the CoC to someone, they should be able to add a footnote
with a reference to that explanation/resource instead so they do not have
to have the same conversation over and over.

**Comment by kern** [comment]
Ahh makes sense. We could have a section for footnotes, linked via IDs. I see these footnotes as mostly being justification for certain policies and other recommended reading.

As far as format goes, I think we can just use <sup> tags and style them like Wikipedia does. What do you think?

**Comment by kern** [comment]
That was a < sup > tag up there. ^ :)

**Comment by rubinovitz** [comment]
Lol I'm viewing via email so can't see it.

Anyway yes I agree. I think that's how to scale the code of conduct and
education without the CoC being too long, people trying to follow it
missing context, and people trying to enforce it constantly having to
repeat themselves and reinvent the wheel.

Geekfeminist wiki has some interesting history baked into their articles
this way. It's also worth a look if you've never read it.

**Pull request merged**
