### PR TITLE
Remove JB from the list of moderators

### PR DESCRIPTION
**Pull request by nsgomez**
It doesn't seem like @rubinovitz is going to be reinstated, though I'd love to be proven wrong about that.

### CODE REVIEW

**Comment by nsgomez** [comment]
ping @kern @folz @hellyeah @evaz @cassidoo @arirawr @rhallie15 
(Not sure who to ping or if pinging is standard procedure here.)

**Comment by rubinovitz** [comment]
screen shot 2015-12-09 at 7 48 53 pm
Goodnight Moon.

**Comment by hellyeah** [comment]
Before removing admins, I want to ensure there's a clear process in place to give them credit for the work they've done. There's no way we can compensate former admins for the immense amount of time and energy they've put in, but at the least we should recognize their contributions.

**Comment by rubinovitz** [comment]
@hellyeah "There's no way we can compensate former admins for the immense amount of time and energy they've put in"
Dave, I don't know if you realize this, and I hope this criticism is soft enough for you, but that makes no sense. People are compensated for work all the time. The fact you say things like that and then utterly disrespect me with your actions is not going unnoticed.

**Comment by nsgomez** [comment]
Generally we recognize the contributions of active participants in the community by awarding them the opportunity to moderate the group and directly assist in making it better.

**Comment by nsgomez** [comment]
I'm closing this pull pending further developments.

**Pull request closed without merging**
